use std::ffi::c_void;

pub use crate::lora_meta::{LoraKernelMeta, NO_LORA};

#[allow(clippy::too_many_arguments)]
pub unsafe fn lora_shrink(
    stream: *mut c_void,
    x_bf16: *const u16,
    a_ptrs: *const u64,
    buffer: *mut f32,
    token_lora_mapping: *const i32,
    token_indices_sorted: *const i32,
    num_tokens_per_lora: *const i32,
    lora_token_start_loc: *const i32,
    active_lora_ids: *const i32,
    m: i32,
    rank: i32,
    k: i32,
    n_slices: i32,
    grid_loras: i32,
    a_d0_stride: i64,
    scale: f32,
) -> i32 {
    crate::nv_kernels_lora_shrink(
        stream,
        x_bf16,
        a_ptrs,
        buffer,
        token_lora_mapping,
        token_indices_sorted,
        num_tokens_per_lora,
        lora_token_start_loc,
        active_lora_ids,
        m,
        rank,
        k,
        n_slices,
        grid_loras,
        a_d0_stride,
        scale,
    )
}

#[allow(clippy::too_many_arguments)]
pub unsafe fn lora_fused(
    stream: *mut c_void,
    x_bf16: *const u16,
    a_ptrs: *const u64,
    b_ptrs: *const u64,
    y_bf16: *mut u16,
    token_indices_sorted: *const i32,
    num_tokens_per_lora: *const i32,
    lora_token_start_loc: *const i32,
    active_lora_ids: *const i32,
    slice_n: *const i32,
    slice_start: *const i32,
    b_d0_stride: *const i64,
    m: i32,
    rank: i32,
    k: i32,
    max_n: i32,
    n_slices: i32,
    grid_loras: i32,
    a_d0_stride: i64,
    win_off: i32,
    win_len: i32,
    y_row_stride: i32,
    scale: f32,
) -> i32 {
    crate::nv_kernels_lora_fused(
        stream,
        x_bf16,
        a_ptrs,
        b_ptrs,
        y_bf16,
        token_indices_sorted,
        num_tokens_per_lora,
        lora_token_start_loc,
        active_lora_ids,
        slice_n,
        slice_start,
        b_d0_stride,
        m,
        rank,
        k,
        max_n,
        n_slices,
        grid_loras,
        a_d0_stride,
        win_off,
        win_len,
        y_row_stride,
        scale,
    )
}

#[allow(clippy::too_many_arguments)]
pub unsafe fn lora_expand(
    stream: *mut c_void,
    buffer: *const f32,
    b_ptrs: *const u64,
    y_bf16: *mut u16,
    token_lora_mapping: *const i32,
    token_indices_sorted: *const i32,
    num_tokens_per_lora: *const i32,
    lora_token_start_loc: *const i32,
    active_lora_ids: *const i32,
    slice_n: *const i32,
    slice_start: *const i32,
    m: i32,
    rank: i32,
    max_n: i32,
    n_slices: i32,
    grid_loras: i32,
    y_row_stride: i32,
) -> i32 {
    crate::nv_kernels_lora_expand(
        stream,
        buffer,
        b_ptrs,
        y_bf16,
        token_lora_mapping,
        token_indices_sorted,
        num_tokens_per_lora,
        lora_token_start_loc,
        active_lora_ids,
        slice_n,
        slice_start,
        m,
        rank,
        max_n,
        n_slices,
        grid_loras,
        y_row_stride,
    )
}
