from __future__ import annotations

P_THRESHOLD = 0.5
MIN_DELAY_MS = 500
MAX_DELAY_MS = 3000
SILENCE_HARD_CAP_MS = 5000
INFERENCE_TIMEOUT_MS = 250
CONTEXT_TURNS = 4
MAX_CONTEXT_TOKENS = 128
AUDIO_WINDOW_MS = 8000
CURVE_K = 12.0
FAILURE_P_DEFAULT = 1.0

FUSION_WEIGHT_TEXT = 0.5
FUSION_RULE = "gated"

CURVE_K_MAX = 30.0
SILENCE_HARD_CAP_MS_MAX = 60_000
INFERENCE_TIMEOUT_MS_MAX = 10_000
CONTEXT_TURNS_MAX = 64
SESSION_MAX_DURATION_S_MAX = 86_400

EAGER_P_THRESHOLD_DISABLED = 1.0
EAGER_P_THRESHOLD = 0.5
EAGER_MAX_INFLIGHT = 1
EAGER_PERIODIC_ENABLED = False
EAGER_INTERVAL_MS = 250
PREDICTED_TOKEN_BUFFER_CAP = 256
EOT_THRESHOLD = 0.7
EAGER_EOT_THRESHOLD = 0.5
EAGER_TRANSCRIPT_MISMATCH_RATIO = 0.5

INPUT_IDS = "input_ids"
ATTENTION_MASK = "attention_mask"
OUTPUT_LOGITS = "logits"

IM_START = "<|im_start|>"
IM_END = "<|im_end|>"

EAGERNESS_LOW = (0.7, 800, 3000)
EAGERNESS_MEDIUM = (0.5, 500, 2500)
EAGERNESS_HIGH = (0.4, 300, 1500)

AUDIO_SAMPLE_RATE = 16_000
AUDIO_N_MELS = 80
AUDIO_N_FFT = 400
AUDIO_HOP_LENGTH = 160
AUDIO_CHUNK_LENGTH_S = 8
AUDIO_TARGET_SAMPLES = AUDIO_CHUNK_LENGTH_S * AUDIO_SAMPLE_RATE
AUDIO_N_FRAMES = AUDIO_TARGET_SAMPLES // AUDIO_HOP_LENGTH

MIN_SPEECH_FOR_RESPONSE_MS = 600
