from __future__ import annotations

from .bpe import BPETokenizer, decode_bpe, encode_bpe
from .constants import (
    DEFAULT_N_MELS,
    LARGE_V3_N_MELS,
    LANGUAGE_CODES,
    SILENCE_PEAK_THRESHOLD,
    WHISPER_CHUNK_SECS,
    WHISPER_HOP_LENGTH,
    WHISPER_NB_FRAMES,
    WHISPER_NFFT,
    WHISPER_PAD_SAMPLES,
    WHISPER_SAMPLING_HZ,
    WHISPER_TIMESTAMP_STEP_MS,
    WHISPER_TIMESTAMP_TOKEN_COUNT,
)
from .mel import (
    MelExtractor,
    build_hann_window,
    build_mel_filters,
    hz_to_mel,
    log_mel_spectrogram,
    mel_to_hz,
    pad_or_truncate_to_30s,
)
from .noise_gate import (
    FULL_MS,
    LOOSE_FLOOR,
    OFF_MS,
    GateThresholds,
    NoiseRejection,
    effective_avg_logprob_threshold,
    evaluate,
)
from .segments import transcribe_long
from .whisper_cpp import WhisperCppBackend, WhisperCppConfig
from .whisper import (
    Backend,
    TimedSegment,
    TranscriptionResult,
    WhisperBackend,
    classify_timestamp,
    join_segments,
    parse_timestamp_token,
    peak_amplitude,
    split_ct2_segments,
    strip_special_tokens,
)

__all__ = [
    "Backend",
    "BPETokenizer",
    "DEFAULT_N_MELS",
    "FULL_MS",
    "GateThresholds",
    "LANGUAGE_CODES",
    "LARGE_V3_N_MELS",
    "LOOSE_FLOOR",
    "MelExtractor",
    "NoiseRejection",
    "OFF_MS",
    "SILENCE_PEAK_THRESHOLD",
    "TimedSegment",
    "TranscriptionResult",
    "WHISPER_CHUNK_SECS",
    "WHISPER_HOP_LENGTH",
    "WHISPER_NB_FRAMES",
    "WHISPER_NFFT",
    "WHISPER_PAD_SAMPLES",
    "WHISPER_SAMPLING_HZ",
    "WHISPER_TIMESTAMP_STEP_MS",
    "WHISPER_TIMESTAMP_TOKEN_COUNT",
    "WhisperBackend",
    "WhisperCppBackend",
    "WhisperCppConfig",
    "build_hann_window",
    "build_mel_filters",
    "classify_timestamp",
    "decode_bpe",
    "effective_avg_logprob_threshold",
    "encode_bpe",
    "evaluate",
    "hz_to_mel",
    "join_segments",
    "log_mel_spectrogram",
    "mel_to_hz",
    "pad_or_truncate_to_30s",
    "parse_timestamp_token",
    "peak_amplitude",
    "split_ct2_segments",
    "strip_special_tokens",
    "transcribe_long",
]
