(* AUTO-GENERATED by rocq/gen/claims.py -- DO NOT EDIT; re-run gen/run.sh.

   Every constant below was read out of a pinned checkpoint at generation
   time, not transcribed by hand: re-pin the model and the constants move,
   and any theorem that stops holding fails this build instead of rotting.

   Each theorem is a REFUTATION stated so that it is false if the claim is
   importable. `2 * (m1 - cut) > m1` says: a lever that removes only `cut`
   bytes from the M=1 compulsory read cannot reach 2x, because Amdahl caps
   it at m1 / (m1 - cut). The claims themselves, their sources and the
   ones this file does NOT bound are in rocq/gen/claims.json. *)

From Stdlib Require Import ZArith Lia.
Open Scope Z_scope.

(* T1.1a-nvfp4-kv-half -- NVFP4 KV cache (note item #1) *)
(* claim: NVFP4 KV gives ~50% KV memory vs FP8. *)
(* checkpoint bytes/elem = 9/16 (0.5625) vs baseline 1; actual cut 43.75%, claimed 50.00% *)
Definition T1_1a_nvfp4_kv_half_quant_bytes : Z := 589824.
Definition T1_1a_nvfp4_kv_half_logical_elems : Z := 1048576.
(* claimed cut 1/2 against a 1 B/elem baseline; refuted iff
   the surviving bytes exceed the claimed survivor share *)
Theorem T1_1a_nvfp4_kv_half_cut_overstated :
  2 * T1_1a_nvfp4_kv_half_quant_bytes > (2 - 1) * T1_1a_nvfp4_kv_half_logical_elems.
Proof. unfold T1_1a_nvfp4_kv_half_quant_bytes, T1_1a_nvfp4_kv_half_logical_elems; lia. Qed.

(* T1.1b-nvfp4-kv-500k-ceiling -- NVFP4 KV cache (note item #1) *)
(* claim: NVFP4 KV doubles the 254K fp8-KV capacity ceiling to ~500K in the same VRAM. *)
(* claimed operating point 500000 tokens vs declared max_position_embeddings 262144 in gemma-4-31b-it-nvfp4 config.json; the claimed point lies outside the declared context *)
Definition T1_1b_nvfp4_kv_500k_ceiling_max_position_embeddings : Z := 262144.
Theorem T1_1b_nvfp4_kv_500k_ceiling_outside_declared_context :
  500000 > T1_1b_nvfp4_kv_500k_ceiling_max_position_embeddings.
Proof. unfold T1_1b_nvfp4_kv_500k_ceiling_max_position_embeddings; lia. Qed.

(* T1.2-moet-2bit-experts -- vLLM-Moet (note item #2) *)
(* claim: 2-bit routed experts halve the dominant M=1 term (expert-weight bytes), up to ~2x on the weight-read-bound M=1 decode term. *)
(* M=1 compulsory read 3,873,048,576 B; routed_expert active 566,238,720 B = 14.62%; removing 283,119,360 B caps the speedup at 1.0789x, claim is 2.0000x *)
Definition T1_2_moet_2bit_experts_m1_bytes : Z := 3873048576.
Definition T1_2_moet_2bit_experts_cut_bytes : Z := 283119360.
Theorem T1_2_moet_2bit_experts_unattainable :
  2 * (T1_2_moet_2bit_experts_m1_bytes - T1_2_moet_2bit_experts_cut_bytes) > 1 * T1_2_moet_2bit_experts_m1_bytes.
Proof. unfold T1_2_moet_2bit_experts_m1_bytes, T1_2_moet_2bit_experts_cut_bytes; lia. Qed.

(* T1.2b-bitsmoe-3bit-experts -- BitsMoE (note item #4) *)
(* claim: Average ~3.0-3.3 bit routed experts give ~1.2-1.3x on the weight-read term. *)
(* M=1 compulsory read 3,873,048,576 B; routed_expert active 566,238,720 B = 14.62%; removing 120,325,728 B caps the speedup at 1.0321x, claim is 1.2000x *)
Definition T1_2b_bitsmoe_3bit_experts_m1_bytes : Z := 3873048576.
Definition T1_2b_bitsmoe_3bit_experts_cut_bytes : Z := 120325728.
Theorem T1_2b_bitsmoe_3bit_experts_unattainable :
  6 * (T1_2b_bitsmoe_3bit_experts_m1_bytes - T1_2b_bitsmoe_3bit_experts_cut_bytes) > 5 * T1_2b_bitsmoe_3bit_experts_m1_bytes.
Proof. unfold T1_2b_bitsmoe_3bit_experts_m1_bytes, T1_2b_bitsmoe_3bit_experts_cut_bytes; lia. Qed.

(* T1.4-not-gated-deltanet -- our-models scope note (exclusion of the Qwen3-Next paper family) *)
(* claim: Deliberately EXCLUDED Qwen3-Next Gated DeltaNet: our Qwen3.6-35B-A3B is standard MoE attention, not the hybrid-linear Next variant. *)
(* linear_attn_layers=30, self_attn_layers=10 (of 40 layers) *)
Definition T1_4_not_gated_deltanet_linear_attn_layers : Z := 30.
Definition T1_4_not_gated_deltanet_self_attn_layers : Z := 10.
Theorem T1_4_not_gated_deltanet_census_total : T1_4_not_gated_deltanet_linear_attn_layers + T1_4_not_gated_deltanet_self_attn_layers = 40.
Proof. unfold T1_4_not_gated_deltanet_linear_attn_layers, T1_4_not_gated_deltanet_self_attn_layers; lia. Qed.
Theorem T1_4_not_gated_deltanet_linear_attn_layers_nonzero : T1_4_not_gated_deltanet_linear_attn_layers > 0.
Proof. unfold T1_4_not_gated_deltanet_linear_attn_layers; lia. Qed.

