(* AUTO-GENERATED by rocq/gen/extract/pdl_sites.py -- DO NOT EDIT;
   re-run rocq/gen/run.sh.  `run.sh --check` fails when this file and the
   CUDA it describes have drifted apart, which is the whole reason it
   exists: the hand-written table it replaces carried twelve source line
   numbers as hypotheses, Rocq never compared one of them to a .cu, and
   all twelve were wrong while the proofs stayed green.

   PdlOrder.v is the rule, PdlKernels.v is the pairing, this is the
   position data.  Every number below is an OUTPUT, read out of the file
   named beside it on the run that wrote this, at the sha256s recorded in
   gen/out/pdl_sites.json.

   DERIVED: the prolog and epilog sites, and the two point sets --
   `<symbol>_every_store_line` (every assignment through a subscript or a
   dereference anywhere in the body) and `<symbol>_every_dereference_line`
   (every subscript or dereference at all).  Both are over-approximations
   on purpose: they cover shared memory, local arrays and untracked
   buffers, so `every store precedes the epilog` and `the prolog precedes
   every dereference` are strictly stronger than the per-buffer
   obligations PdlOrder states, and imply them.  Nobody hand-picks a last
   write, so nobody can pick the wrong one.

   DECLARED, in gen/pdl_kernels.json: which __global__ symbol each record
   models, and which buffer each parameter carries -- each witnessed by
   the exact source text of the parameter declaration, required to occur
   exactly once in that kernel's parameter list.
*)

From Stdlib Require Import List Arith.
Import ListNotations.
From SpeachesPlus Require Import PdlOrder.

Lemma every_member_below :
  forall n l, forallb (fun p => Nat.ltb p n) l = true -> forall p, In p l -> p < n.
Proof.
  intros n l. induction l as [| a l IH]; intros H p Hp; [contradiction |].
  simpl in H. destruct (Nat.ltb a n) eqn:Ha; simpl in H; [| discriminate].
  destruct Hp as [Hp | Hp];
  [subst; apply Nat.ltb_lt; exact Ha | apply IH; assumption].
Qed.

Lemma every_member_above :
  forall n l, forallb (fun p => Nat.ltb n p) l = true -> forall p, In p l -> n < p.
Proof.
  intros n l. induction l as [| a l IH]; intros H p Hp; [contradiction |].
  simpl in H. destruct (Nat.ltb n a) eqn:Ha; simpl in H; [| discriminate].
  destruct Hp as [Hp | Hp];
  [subst; apply Nat.ltb_lt; exact Ha | apply IH; assumption].
Qed.

Definition b_resid : buffer := 0.
Definition b_norm : buffer := 1.
Definition b_gemv : buffer := 2.
Definition b_q : buffer := 3.
Definition b_k : buffer := 4.
Definition b_scales : buffer := 5.
Definition b_fp8 : buffer := 6.
Definition b_out : buffer := 7.

(* residual_add_scale_bf16_kernel  rust/crates/nv-kernels/cuda/residual_scale.cu:10
   body 16-26, prolog 17, epilog 25
   produces b_resid: `__nv_bfloat16*        __restrict__ y` at :12
*)
Definition residual_add_scale_bf16_kernel_every_store_line : list point := [23].
Definition residual_add_scale_bf16_kernel_every_dereference_line : list point := [21; 22; 23].
Definition residual_add_scale_bf16_kernel_epilog_line : point := 25.
Definition kResidual : kernel :=
  {| k_id := 0; k_prolog := 17;
     k_epilog := residual_add_scale_bf16_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_resid then residual_add_scale_bf16_kernel_every_store_line else [];
     k_reads := fun b =>
       [] |}.

Theorem kResidual_prolog_precedes_every_dereference :
  forall p, In p residual_add_scale_bf16_kernel_every_dereference_line -> k_prolog kResidual < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kResidual_epilog_follows_every_store :
  forall p, In p residual_add_scale_bf16_kernel_every_store_line -> p < k_epilog kResidual.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kResidual_writes_b_resid_before_epilog : epilog_after_writes kResidual b_resid.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Definition residual_add_scale_bf16_kernel_launched_with_programmatic_serialization : bool := true.

(* rmsnorm_kernel  rust/crates/nv-kernels/cuda/rmsnorm.cu:47
   body 51-72, prolog 56, epilog 71
   consumes b_resid: `const T* __restrict__ x` at :47
   produces b_norm: `T* __restrict__ y` at :48
*)
Definition rmsnorm_kernel_every_store_line : list point := [68].
Definition rmsnorm_kernel_every_dereference_line : list point := [60; 67; 68].
Definition rmsnorm_kernel_epilog_line : point := 71.
Definition kRmsnorm : kernel :=
  {| k_id := 1; k_prolog := 56;
     k_epilog := rmsnorm_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_norm then rmsnorm_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_resid then rmsnorm_kernel_every_dereference_line else [] |}.

Theorem kRmsnorm_prolog_precedes_every_dereference :
  forall p, In p rmsnorm_kernel_every_dereference_line -> k_prolog kRmsnorm < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kRmsnorm_epilog_follows_every_store :
  forall p, In p rmsnorm_kernel_every_store_line -> p < k_epilog kRmsnorm.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kRmsnorm_writes_b_norm_before_epilog : epilog_after_writes kRmsnorm b_norm.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kRmsnorm_reads_b_resid_after_prolog : prolog_before_reads kRmsnorm b_resid.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition rmsnorm_kernel_launched_with_programmatic_serialization : bool := true.

(* gemv_bf16_kernel  rust/crates/nv-kernels/cuda/gemv_bf16.cu:21
   body 27-74, prolog 28, epilog 73
   consumes b_norm: `const __nv_bfloat16* __restrict__ x` at :22
   produces b_gemv: `__nv_bfloat16* __restrict__ y` at :23
*)
Definition gemv_bf16_kernel_every_store_line : list point := [33; 71].
Definition gemv_bf16_kernel_every_dereference_line : list point := [30; 33; 49; 54; 57; 58; 60; 61; 71].
Definition gemv_bf16_kernel_epilog_line : point := 73.
Definition kGemv : kernel :=
  {| k_id := 2; k_prolog := 28;
     k_epilog := gemv_bf16_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_gemv then gemv_bf16_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_norm then gemv_bf16_kernel_every_dereference_line else [] |}.

Theorem kGemv_prolog_precedes_every_dereference :
  forall p, In p gemv_bf16_kernel_every_dereference_line -> k_prolog kGemv < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kGemv_epilog_follows_every_store :
  forall p, In p gemv_bf16_kernel_every_store_line -> p < k_epilog kGemv.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kGemv_writes_b_gemv_before_epilog : epilog_after_writes kGemv b_gemv.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kGemv_reads_b_norm_after_prolog : prolog_before_reads kGemv b_norm.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition gemv_bf16_kernel_launched_with_programmatic_serialization : bool := true.

(* rope_bf16_oop_kernel  rust/crates/nv-kernels/cuda/rope_bf16.cu:76
   body 87-123, prolog 88, epilog 122
   consumes b_gemv: `const __nv_bfloat16* __restrict__ q_in` at :76
   consumes b_gemv: `const __nv_bfloat16* __restrict__ k_in` at :77
   produces b_k: `__nv_bfloat16* __restrict__ k_out` at :79
   produces b_q: `__nv_bfloat16* __restrict__ q_out` at :78
*)
Definition rope_bf16_oop_kernel_every_store_line : list point := [111; 112; 118; 119].
Definition rope_bf16_oop_kernel_every_dereference_line : list point := [97; 101; 102; 109; 110; 111; 112; 116; 117; 118; 119].
Definition rope_bf16_oop_kernel_epilog_line : point := 122.
Definition kRope : kernel :=
  {| k_id := 3; k_prolog := 88;
     k_epilog := rope_bf16_oop_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_k then rope_bf16_oop_kernel_every_store_line else if Nat.eqb b b_q then rope_bf16_oop_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_gemv then rope_bf16_oop_kernel_every_dereference_line else [] |}.

Theorem kRope_prolog_precedes_every_dereference :
  forall p, In p rope_bf16_oop_kernel_every_dereference_line -> k_prolog kRope < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kRope_epilog_follows_every_store :
  forall p, In p rope_bf16_oop_kernel_every_store_line -> p < k_epilog kRope.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kRope_writes_b_k_before_epilog : epilog_after_writes kRope b_k.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kRope_writes_b_q_before_epilog : epilog_after_writes kRope b_q.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kRope_reads_b_gemv_after_prolog : prolog_before_reads kRope b_gemv.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition rope_bf16_oop_kernel_launched_with_programmatic_serialization : bool := true.

(* quantize_kv_fp8_kernel  rust/crates/nv-kernels/cuda/kv_fp8.cu:23
   body 32-81, prolog 33, epilog 80
   consumes b_k: `const __nv_bfloat16* __restrict__ x_bf16` at :23
   produces b_fp8: `uint8_t* __restrict__ x_fp8_base` at :24
   produces b_scales: `float* __restrict__ scales_base` at :25
*)
Definition quantize_kv_fp8_kernel_every_store_line : list point := [57; 63; 71; 77].
Definition quantize_kv_fp8_kernel_every_dereference_line : list point := [39; 48; 54; 57; 61; 63; 66; 71; 75; 77].
Definition quantize_kv_fp8_kernel_epilog_line : point := 80.
Definition kKvFp8 : kernel :=
  {| k_id := 4; k_prolog := 33;
     k_epilog := quantize_kv_fp8_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_fp8 then quantize_kv_fp8_kernel_every_store_line else if Nat.eqb b b_scales then quantize_kv_fp8_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_k then quantize_kv_fp8_kernel_every_dereference_line else [] |}.

Theorem kKvFp8_prolog_precedes_every_dereference :
  forall p, In p quantize_kv_fp8_kernel_every_dereference_line -> k_prolog kKvFp8 < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kKvFp8_epilog_follows_every_store :
  forall p, In p quantize_kv_fp8_kernel_every_store_line -> p < k_epilog kKvFp8.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kKvFp8_writes_b_fp8_before_epilog : epilog_after_writes kKvFp8 b_fp8.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kKvFp8_writes_b_scales_before_epilog : epilog_after_writes kKvFp8 b_scales.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kKvFp8_reads_b_k_after_prolog : prolog_before_reads kKvFp8 b_k.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition quantize_kv_fp8_kernel_launched_with_programmatic_serialization : bool := true.

(* flash_splitk_fused_fp8_kernel  rust/crates/nv-kernels/cuda/flash_decode.cu:985
   body 1003-1249, prolog 1008, epilog 1248
   consumes b_fp8: `const uint8_t* __restrict__ k_fp8` at :986
   consumes b_q: `const __nv_bfloat16* __restrict__ q` at :985
   consumes b_scales: `const float* __restrict__ k_scales` at :988
   produces b_out: `__nv_bfloat16* __restrict__ outp` at :992
*)
Definition flash_splitk_fused_fp8_kernel_every_store_line : list point := [1020; 1025; 1047; 1052; 1082; 1083; 1084; 1085; 1086; 1087; 1088; 1089; 1139; 1140; 1141; 1142; 1143; 1144; 1145; 1146; 1153; 1166; 1167; 1173; 1179; 1194; 1195; 1207; 1231; 1244; 1246].
Definition flash_splitk_fused_fp8_kernel_every_dereference_line : list point := [1010; 1018; 1020; 1023; 1025; 1039; 1040; 1041; 1042; 1047; 1052; 1057; 1063; 1064; 1065; 1066; 1077; 1082; 1083; 1084; 1085; 1086; 1087; 1088; 1089; 1097; 1103; 1109; 1110; 1111; 1112; 1116; 1117; 1128; 1134; 1139; 1140; 1141; 1142; 1143; 1144; 1145; 1146; 1153; 1154; 1155; 1162; 1163; 1164; 1166; 1167; 1173; 1179; 1188; 1192; 1194; 1195; 1201; 1206; 1207; 1213; 1219; 1225; 1230; 1231; 1232; 1243; 1244; 1246].
Definition flash_splitk_fused_fp8_kernel_epilog_line : point := 1248.
Definition kFlash : kernel :=
  {| k_id := 5; k_prolog := 1008;
     k_epilog := flash_splitk_fused_fp8_kernel_epilog_line;
     k_writes := fun b =>
       if Nat.eqb b b_out then flash_splitk_fused_fp8_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_fp8 then flash_splitk_fused_fp8_kernel_every_dereference_line else if Nat.eqb b b_q then flash_splitk_fused_fp8_kernel_every_dereference_line else if Nat.eqb b b_scales then flash_splitk_fused_fp8_kernel_every_dereference_line else [] |}.

Theorem kFlash_prolog_precedes_every_dereference :
  forall p, In p flash_splitk_fused_fp8_kernel_every_dereference_line -> k_prolog kFlash < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kFlash_epilog_follows_every_store :
  forall p, In p flash_splitk_fused_fp8_kernel_every_store_line -> p < k_epilog kFlash.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kFlash_writes_b_out_before_epilog : epilog_after_writes kFlash b_out.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kFlash_reads_b_fp8_after_prolog : prolog_before_reads kFlash b_fp8.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Lemma kFlash_reads_b_q_after_prolog : prolog_before_reads kFlash b_q.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Lemma kFlash_reads_b_scales_after_prolog : prolog_before_reads kFlash b_scales.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition flash_splitk_fused_fp8_kernel_launched_with_programmatic_serialization : bool := true.

(* flash_splitk_fused_fp8_derivev_kernel  rust/crates/nv-kernels/cuda/flash_decode.cu:749
   body 769-982, prolog 774, no explicit epilog; kernel exit at 982
   consumes b_fp8: `const uint8_t* __restrict__ k_fp8` at :750
   consumes b_q: `const __nv_bfloat16* __restrict__ q` at :749
   consumes b_scales: `const float* __restrict__ k_scales` at :751
   produces b_out: `__nv_bfloat16* __restrict__ outp` at :757
*)
Definition flash_splitk_fused_fp8_derivev_kernel_every_store_line : list point := [786; 791; 813; 823; 824; 825; 826; 856; 857; 870; 871; 897; 898; 908; 909; 915; 929; 930; 942; 966; 979; 981].
Definition flash_splitk_fused_fp8_derivev_kernel_every_dereference_line : list point := [776; 784; 786; 789; 791; 805; 809; 813; 815; 818; 823; 824; 825; 826; 833; 834; 835; 836; 853; 856; 857; 870; 871; 879; 881; 891; 892; 893; 894; 897; 898; 904; 905; 906; 908; 909; 915; 923; 927; 929; 930; 936; 941; 942; 948; 954; 960; 965; 966; 967; 978; 979; 981].
Definition flash_splitk_fused_fp8_derivev_kernel_epilog_is_kernel_exit_no_explicit_trigger : point := 982.
Definition kFlashDeriveV : kernel :=
  {| k_id := 6; k_prolog := 774;
     k_epilog := flash_splitk_fused_fp8_derivev_kernel_epilog_is_kernel_exit_no_explicit_trigger;
     k_writes := fun b =>
       if Nat.eqb b b_out then flash_splitk_fused_fp8_derivev_kernel_every_store_line else [];
     k_reads := fun b =>
       if Nat.eqb b b_fp8 then flash_splitk_fused_fp8_derivev_kernel_every_dereference_line else if Nat.eqb b b_q then flash_splitk_fused_fp8_derivev_kernel_every_dereference_line else if Nat.eqb b b_scales then flash_splitk_fused_fp8_derivev_kernel_every_dereference_line else [] |}.

Theorem kFlashDeriveV_prolog_precedes_every_dereference :
  forall p, In p flash_splitk_fused_fp8_derivev_kernel_every_dereference_line -> k_prolog kFlashDeriveV < p.
Proof. apply every_member_above. vm_compute. reflexivity. Qed.

Theorem kFlashDeriveV_epilog_follows_every_store :
  forall p, In p flash_splitk_fused_fp8_derivev_kernel_every_store_line -> p < k_epilog kFlashDeriveV.
Proof. apply every_member_below. vm_compute. reflexivity. Qed.

Lemma kFlashDeriveV_writes_b_out_before_epilog : epilog_after_writes kFlashDeriveV b_out.
Proof. unfold epilog_after_writes. apply every_member_below.
       vm_compute. reflexivity. Qed.

Lemma kFlashDeriveV_reads_b_fp8_after_prolog : prolog_before_reads kFlashDeriveV b_fp8.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Lemma kFlashDeriveV_reads_b_q_after_prolog : prolog_before_reads kFlashDeriveV b_q.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Lemma kFlashDeriveV_reads_b_scales_after_prolog : prolog_before_reads kFlashDeriveV b_scales.
Proof. unfold prolog_before_reads. apply every_member_above.
       vm_compute. reflexivity. Qed.

Definition flash_splitk_fused_fp8_derivev_kernel_launched_with_programmatic_serialization : bool := false.

(* Census, in both directions, as data rather than as a claim in a commit
   message.  Every prolog and epilog in the declared corpus sits inside a
   modelled kernel, and every cudaLaunchKernelEx callee is a modelled
   kernel -- that call is how this repo passes
   cudaLaunchAttributeProgrammaticStreamSerialization, through NVK_PDL_ATTR
   and hand-rolled alike. *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:774 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:1008 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:1248 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/gemv_bf16.cu:28 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/gemv_bf16.cu:73 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/kv_fp8.cu:33 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/kv_fp8.cu:80 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/residual_scale.cu:17 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/residual_scale.cu:25 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/rmsnorm.cu:56 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/rmsnorm.cu:71 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/rope_bf16.cu:88 NVK_PDL_PROLOG *)
(*   rust/crates/nv-kernels/cuda/rope_bf16.cu:122 NVK_PDL_EPILOG *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:1552 launches flash_splitk_fused_fp8_kernel *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:1559 launches flash_splitk_fused_fp8_kernel *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu:1566 launches flash_splitk_fused_fp8_kernel *)
(*   rust/crates/nv-kernels/cuda/gemv_bf16.cu:438 launches gemv_bf16_kernel *)
(*   rust/crates/nv-kernels/cuda/kv_fp8.cu:134 launches quantize_kv_fp8_kernel *)
(*   rust/crates/nv-kernels/cuda/residual_scale.cu:68 launches residual_add_scale_bf16_kernel *)
(*   rust/crates/nv-kernels/cuda/rmsnorm.cu:87 launches rmsnorm_kernel *)
(*   rust/crates/nv-kernels/cuda/rmsnorm.cu:107 launches rmsnorm_kernel *)
(*   rust/crates/nv-kernels/cuda/rope_bf16.cu:146 launches rope_bf16_oop_kernel *)
Definition pdl_prolog_sites_in_corpus : nat := 7.
Definition pdl_epilog_sites_in_corpus : nat := 6.
Definition pdl_kernels_modelled : nat := 7.
Definition pdl_launch_sites_in_corpus : nat := 9.

Theorem every_wired_kernel_is_modelled :
  pdl_prolog_sites_in_corpus = pdl_kernels_modelled.
Proof. reflexivity. Qed.

(* Modelled kernels whose PDL wiring is INCOMPLETE in the CUDA.  Each is
   safe -- without an explicit trigger the launch completes at kernel
   exit, and a kernel nothing launches with programmatic serialization
   is serialized the ordinary way (PdlOrder.unwired_neighbour_is_safe)
   -- but each is also a prolog that buys nothing today. *)
(*   flash_splitk_fused_fp8_derivev_kernel: explicit epilog false, launched with programmatic serialization false *)
Definition pdl_kernels_with_incomplete_wiring : nat := 1.

(* The sources this file was read out of. *)
(*   rust/crates/nv-kernels/cuda/flash_decode.cu 45b30793c3f7d84d7a0453198024561add432bbc96c59b211c25d7e5a862fa59 *)
(*   rust/crates/nv-kernels/cuda/gemv_bf16.cu 3cde1fd680cf99ebc9de7912295a63805fcc379fb5e45035350a79994f75eb84 *)
(*   rust/crates/nv-kernels/cuda/kv_fp8.cu 7377c398b510476c74dc51ff37a0c93a99670fb6331130e6c019df42f05302f9 *)
(*   rust/crates/nv-kernels/cuda/residual_scale.cu 7a75a134077d2c5f2762fd6ede050f8e56a4e4efeb561efa022b94795c8ce8bc *)
(*   rust/crates/nv-kernels/cuda/rmsnorm.cu f4701eb1e7b3e028a96bf2fc2cadb6be0bb7ad77bdb51152c04798c4b6c0e49d *)
(*   rust/crates/nv-kernels/cuda/rope_bf16.cu 0377c3cf07b21f1b9caf19c136b9035469199f2700bdff38ab72f0bbe75356ab *)
