(* AUTO-GENERATED by rocq/gen/gen.py on 2026-08-10 06:35 -- DO NOT EDIT; re-run gen/run.sh.
   verifier config: /nix/store/<hash>-hf-model-nvidia-Gemma-4-31B-IT-NVFP4-e5ef03afa233c35cb000323ff098d4291e1dd07c/config.json
   drafter  config: /nix/store/<hash>-hf-model-RedHatAI-gemma-4-31B-it-speculator.eagle3-28a1c8b4bb64dbaee883ba35341841138bdf1fe3/config.json
   machine:  1790000000000 B/s HBM, 268435456 B L2-residency credit (1.79 TB/s nominal part peak, used as the UPPER-bound physics hypothesis; measured achieved read BW recorded separately below and checked <= this at generation time)
   measured: ../../docs/measurements/2026-08-10-rocq-repoint/server-prof.txt
             (8/18 summaries with rounds>=50; verify 27.47-27.86 ms, draft 3.21-3.23 ms/round, tokens/round 2.46-2.67, K=4 shift)
             ../../docs/measurements/2026-08-10-rocq-repoint/bench.json aggregate 83.18 tok/s over 2040 tokens *)

From Stdlib Require Import Reals Lra Psatz ZArith.
From SpeachesPlus Require Import Roofline GenTraffic.
Open Scope R_scope.

(* Machine constants (gen/machine.json). *)
Definition BW : R := 1790000000000.
Definition L2 : R := 268435456.
Lemma BW_pos : 0 < BW. Proof. unfold BW; lra. Qed.

(* Weight traffic constants, imported from the checked Z development. *)
Definition Wv : R := IZR GenTraffic.verify_weight_bytes.
Lemma Wv_val : Wv = 31481767960.
Proof. unfold Wv; rewrite GenTraffic.verify_weight_bytes_val; lra. Qed.
Lemma Wv_gt_L2 : L2 < Wv. Proof. rewrite Wv_val; unfold L2; lra. Qed.

Definition Wd : R := IZR GenTraffic.draft_step_weight_bytes.
Lemma Wd_val : Wd = 1478141952.
Proof. unfold Wd; rewrite GenTraffic.draft_step_weight_bytes_val; lra. Qed.
Lemma Wd_gt_L2 : L2 < Wd. Proof. rewrite Wd_val; unfold L2; lra. Qed.

(* Traffic lower-bound hypothesis for phases whose compulsory bytes exceed
   the weight stream (verify at large ctx adds the committed-KV read). Same
   physics as Roofline.weight_traffic_lb, stated over total bytes. *)
Definition traffic_lb (B : R) (f : forward_exec) : Prop := B <= hbm_bytes f.

(* =============== (ii) lower bounds on THIS GPU =============== *)

(* Verify weight floor: 17.438 ms exact; stated at ns precision. *)
Theorem gen_verify_weight_floor :
  forall f, respects_bandwidth BW f -> weight_traffic_lb L2 Wv f ->
  3487523 / 200000000 <= wall_time f.
Proof.
  intros f H1 H2.
  pose proof (verify_time_lower_bound BW L2 Wv f H1 H2) as H.
  rewrite Wv_val in H; unfold BW, L2 in *; lra.
Qed.

(* Verify floor at full context 262144: compulsory bytes = weights +
   clamped committed-KV unique reads, credited with the FULL L2 residency
   (weights and KV are disjoint allocations, so one shared credit is the
   weakest safe hypothesis): 23.904 ms exact. *)
Theorem gen_verify_floor_full_ctx :
  forall f, respects_bandwidth BW f ->
  traffic_lb (IZR (GenTraffic.verify_min_traffic 262144) - L2) f ->
  23904353 / 1000000000 <= wall_time f.
Proof.
  intros f H1 H2; unfold respects_bandwidth in H1; unfold traffic_lb in H2.
  rewrite GenTraffic.verify_min_traffic_at_262144 in H2.
  unfold BW, L2 in *; lra.
Qed.

(* Drafter step floor: 675.8 us exact. *)
Theorem gen_draft_step_floor :
  forall f, respects_bandwidth BW f -> weight_traffic_lb L2 Wd f ->
  675813 / 1000000000 <= wall_time f.
Proof.
  intros f H1 H2.
  pose proof (verify_time_lower_bound BW L2 Wd f H1 H2) as H.
  rewrite Wd_val in H; unfold BW, L2 in *; lra.
Qed.

(* Speed-of-light ceiling at the measured best acceptance
   (tokens/round <= 2.67, ../../docs/measurements/2026-08-10-rocq-repoint/server-prof.txt):
   r <= tpr*BW/(Wv-L2) = 153.1 tok/s exact. NOTE: this supersedes
   core Roofline.Measured.token_rate_ceiling_218 -- that instance used the
   road-to-50 W=18.3 GB estimate, which undercounted the bf16 attention
   stream; both are sound, this one is ~1.6x tighter. *)
Theorem gen_token_rate_ceiling :
  forall f T tpr r,
    respects_bandwidth BW f -> weight_traffic_lb L2 Wv f ->
    wall_time f <= T -> 0 <= tpr ->
    tpr <= 267 / 100 -> r * T = tpr ->
    r <= 154.
Proof.
  intros f T tpr r H1 H2 HT Htpr Hub Hr.
  pose proof (speed_of_light BW L2 Wv f T tpr r BW_pos Wv_gt_L2 H1 H2 HT Htpr Hr) as Hsol.
  rewrite Wv_val in Hsol; unfold BW, L2 in *; lra.
Qed.

(* BATCHED ceilings at full ctx. The B=1 hypothesis r*T = tpr in
   gen_token_rate_ceiling fixes a SINGLE stream; a batched forward
   amortizes the weight stream over B sequences while per-sequence KV
   does not amortize. Wkv = kv_read_bytes at full ctx. *)
Definition Wkv : R := IZR (GenTraffic.kv_read_bytes 262144).
Lemma Wkv_val : Wkv = 11575459840.
Proof. unfold Wkv, GenTraffic.kv_read_bytes; cbv; lra. Qed.
Lemma Wkv_nonneg : 0 <= Wkv. Proof. rewrite Wkv_val; lra. Qed.
Lemma Wkv_pos : 0 < Wkv. Proof. rewrite Wkv_val; lra. Qed.

Theorem gen_token_rate_ceiling_batched_16 :
  forall f T tpr r,
    respects_bandwidth BW f ->
    batched_traffic_lb L2 Wv Wkv 16 f ->
    wall_time f <= T -> 0 <= tpr ->
    tpr <= 267 / 100 -> r * T = 16 * tpr ->
    r <= 354.
Proof.
  intros f T tpr r H1 H2 HT Htpr Hub Hr.
  pose proof (speed_of_light_batched BW L2 Wv Wkv 16 f T tpr r
                BW_pos Wv_gt_L2 Wkv_nonneg (ltac:(lra)) H1 H2 HT Htpr Hr) as Hsol.
  rewrite Wv_val, Wkv_val in Hsol; unfold BW, L2 in *; lra.
Qed.

(* No batch size beats this: per-sequence KV traffic is the wall. *)
Theorem gen_token_rate_ceiling_any_batch :
  forall B f T tpr r,
    1 <= B ->
    respects_bandwidth BW f ->
    batched_traffic_lb L2 Wv Wkv B f ->
    wall_time f <= T -> 0 <= tpr ->
    tpr <= 267 / 100 -> r * T = B * tpr ->
    r <= 413.
Proof.
  intros B f T tpr r HB H1 H2 HT Htpr Hub Hr.
  pose proof (batched_ceiling_saturates BW L2 Wv Wkv B f T tpr r
                BW_pos Wv_gt_L2 Wkv_pos HB H1 H2 HT Htpr Hr) as Hsat.
  rewrite Wkv_val in Hsat; unfold BW in *; lra.
Qed.

(* Round-serial ceiling: our engine runs draft (K steps) then verify serially
   (chat_engine round loop), so T >= T_verify + 4*T_draft_step. *)
Definition k_chain : R := 4.
Theorem gen_round_serial_ceiling :
  forall fv fd T tpr r,
    respects_bandwidth BW fv -> weight_traffic_lb L2 Wv fv ->
    respects_bandwidth BW fd -> weight_traffic_lb L2 Wd fd ->
    wall_time fv + k_chain * wall_time fd <= T ->
    0 <= tpr -> tpr <= 267 / 100 -> r * T = tpr ->
    r <= 133.
Proof.
  intros fv fd T tpr r H1 H2 H3 H4 HT Htpr Hub Hr.
  pose proof (verify_time_lower_bound BW L2 Wv fv H1 H2) as Hv.
  pose proof (verify_time_lower_bound BW L2 Wd fd H3 H4) as Hd.
  rewrite Wv_val in Hv; rewrite Wd_val in Hd.
  unfold BW, L2, k_chain in *.
  assert (HTmin : 2014087 / 100000000 <= T) by lra.
  assert (HTpos : 0 < T) by lra.
  assert (Hr0 : 0 <= r) by nra.
  assert (Hkey : r * (2014087 / 100000000) <= tpr) by nra.
  lra.
Qed.

(* =============== (iii) measured efficiency ratios =============== *)

(* Measured envelope: ../../docs/measurements/2026-08-10-rocq-repoint/server-prof.txt,
   8 steady-state summaries (rounds >= 50). *)
Definition measured_verify_lo_s : R := 2747 / 100000.
Definition measured_verify_hi_s : R := 1393 / 50000.
Definition measured_draft_lo_s  : R := 321 / 100000.
Definition measured_draft_hi_s  : R := 323 / 100000.
(* ../../docs/measurements/2026-08-10-rocq-repoint/bench.json: 2040 tokens, aggregate decode rate (rounded down). *)
Definition measured_agg_tok_s   : R := 8317 / 100.

(* Consistency tripwires: the physical floor must sit BELOW every measurement.
   If a manifest edit ever overcounts compulsory bytes, these two lemmas (and
   generation itself) fail -- the manifest cannot silently inflate. *)
Lemma gen_verify_floor_consistent : (Wv - L2) / BW <= measured_verify_lo_s.
Proof. rewrite Wv_val; unfold L2, BW, measured_verify_lo_s; lra. Qed.
Lemma gen_draft_floor_consistent :
  k_chain * ((Wd - L2) / BW) <= measured_draft_lo_s.
Proof. rewrite Wd_val; unfold L2, BW, k_chain, measured_draft_lo_s; lra. Qed.

(* VERIFY is within 1.60x of light: measured worst-case verify wall
   time vs the weight-stream floor. Further verify acceleration beyond this
   factor must either CUT BYTES (algorithm: e.g. quantize the bf16 attention
   stream, fp8 KV) or RAISE BW (hardware) -- no schedule change can pass it. *)
Theorem gen_verify_within_light_ratio :
  measured_verify_hi_s <= 8 / 5 * ((Wv - L2) / BW).
Proof. rewrite Wv_val; unfold measured_verify_hi_s, L2, BW; lra. Qed.

(* DRAFT chain (K=4) is within 1.20x of light. *)
Theorem gen_draft_within_light_ratio :
  measured_draft_hi_s <= 6 / 5 * (k_chain * ((Wd - L2) / BW)).
Proof. rewrite Wd_val; unfold measured_draft_hi_s, k_chain, L2, BW; lra. Qed.

(* END-TO-END: the speed-of-light ceiling (153.1 tok/s at measured
   acceptance) is within 1.86x of the measured aggregate decode rate
   (83.17 tok/s) -- i.e. the whole engine sits within that factor
   of the bandwidth roof. *)
Theorem gen_e2e_within_light_ratio :
  154 <= 93 / 50 * measured_agg_tok_s.
Proof. unfold measured_agg_tok_s; lra. Qed.

(* =============== bandwidth-hypothesis consistency =============== *)

(* The physics hypothesis BW = 1.79 TB/s must upper-bound anything a
   kernel actually achieves.  Best measured contiguous-read bandwidth on this
   GPU (in-tree sol_roofline harness, util-formal lane, in-tree sol_roofline phase A on main @ 4c70177 (utilf/sol-draft.out, 2026-07-28): best contiguous-read 1501.6 GB/s across 3 same-session runs (1420-1502; GPU shared with ~5 GiB foreign tenants); sol-roofline run3 measured 1491. All <= the 1.79 TB/s hypothesis - soundness direction validated.):
   1502 GB/s.  Generation FAILS if this ever exceeds BW. *)
Definition measured_read_bw : R := 1501639356000.
Lemma bw_hypothesis_consistent : measured_read_bw <= BW.
Proof. unfold measured_read_bw, BW; lra. Qed.

(* =============== utilization headline =============== *)

(* Round-phase envelope (worst steady-state summary): verify 27.86 ms +
   draft 3.23 ms + host residue 0.12 ms
   (round wall = tokens/round x ms/token, minus the GPU phases) = 31.21 ms.
   Physical floor of the same round shape: verify 17.44 + K x draft-step
   2.70 = 20.14 ms. *)
Definition measured_host_hi_s : R := 1213 / 10000000.
Definition measured_round_hi_s : R :=
  measured_verify_hi_s + measured_draft_hi_s + measured_host_hi_s.
Definition floor_round_s : R := (Wv - L2) / BW + k_chain * ((Wd - L2) / BW).

(* WHERE THE GAP LIVES -- an exact accounting, not an estimate. The three
   phase gaps sum to the whole round gap by construction; their measured
   values: verify-in-kernel 10.42 ms (94.1%), draft chain
   0.53 ms (4.8%), host 0.12 ms (1.1%). *)
Definition verify_gap_s : R := measured_verify_hi_s - (Wv - L2) / BW.
Definition draft_gap_s  : R := measured_draft_hi_s - k_chain * ((Wd - L2) / BW).
Theorem gen_gap_decomposition :
  measured_round_hi_s - floor_round_s =
  verify_gap_s + draft_gap_s + measured_host_hi_s.
Proof.
  unfold measured_round_hi_s, floor_round_s, verify_gap_s, draft_gap_s. lra.
Qed.

(* The verify in-kernel gap is at least 94% of everything separating
   this engine from its bandwidth floor: closing anything else is bounded
   by the remaining 6%. *)
Theorem gen_gap_lives_in_verify :
  94 / 100 * (measured_round_hi_s - floor_round_s) <= verify_gap_s.
Proof.
  rewrite gen_gap_decomposition.
  unfold verify_gap_s, draft_gap_s, measured_host_hi_s,
    measured_verify_hi_s, measured_draft_hi_s, k_chain, L2, BW.
  rewrite Wv_val, Wd_val. lra.
Qed.

(* THE HEADLINE, machine-checked: any schedule of this model on this GPU at
   the measured acceptance is capped at 154 tok/s, and that cap is at most
   93 / 50x the 83.17 tok/s the merged engine already delivers -- we are
   within 93 / 50x of light, and gen_gap_lives_in_verify locates >= 94% of
   the remaining distance in verify in-kernel efficiency. *)
Theorem gen_util_headline :
  forall f T tpr r,
    respects_bandwidth BW f -> weight_traffic_lb L2 Wv f ->
    wall_time f <= T -> 0 <= tpr ->
    tpr <= 267 / 100 -> r * T = tpr ->
    r <= 93 / 50 * measured_agg_tok_s.
Proof.
  intros f T tpr r H1 H2 HT Htpr Hub Hr.
  pose proof (gen_token_rate_ceiling f T tpr r H1 H2 HT Htpr Hub Hr).
  pose proof gen_e2e_within_light_ratio. lra.
Qed.
