(* AUTO-GENERATED by rocq/gen/gen.py on 2026-08-10 06:35 -- DO NOT EDIT; re-run gen/run.sh.
   verifier config: /nix/store/<hash>-hf-model-nvidia-Gemma-4-31B-IT-NVFP4-e5ef03afa233c35cb000323ff098d4291e1dd07c/config.json
   drafter  config: /nix/store/<hash>-hf-model-RedHatAI-gemma-4-31B-it-speculator.eagle3-28a1c8b4bb64dbaee883ba35341841138bdf1fe3/config.json
   machine:  1790000000000 B/s HBM, 268435456 B L2-residency credit (1.79 TB/s nominal part peak, used as the UPPER-bound physics hypothesis; measured achieved read BW recorded separately below and checked <= this at generation time)
   measured: ../../docs/measurements/2026-08-10-rocq-repoint/server-prof.txt
             (8/18 summaries with rounds>=50; verify 27.47-27.86 ms, draft 3.21-3.23 ms/round, tokens/round 2.46-2.67, K=4 shift)
             ../../docs/measurements/2026-08-10-rocq-repoint/bench.json aggregate 83.18 tok/s over 2040 tokens *)

From Stdlib Require Import ZArith Lia.
Open Scope Z_scope.

(* Shape environment, derived from config.json. *)
Module S.
  (* config.json text_config.hidden_size = 5376 *)
  Definition h : Z := 5376.
  (* config.json text_config.intermediate_size = 21504 *)
  Definition inter : Z := 21504.
  (* config.json text_config.num_hidden_layers = 60 *)
  Definition nlayers : Z := 60.
  (* config.json text_config.layer_types (50 sliding) *)
  Definition n_slide : Z := 50.
  (* config.json text_config.layer_types (10 full, every 6th) *)
  Definition n_full : Z := 10.
  (* config.json = 32 *)
  Definition nh : Z := 32.
  (* config.json = 256 (sliding layers); gemma4.rs:134-139 head_dim_for *)
  Definition hd : Z := 256.
  (* config.json = 16 (sliding layers); gemma4.rs:141-148 num_kv_heads_for *)
  Definition nkv : Z := 16.
  (* config.json = 512 (full-attention layers) *)
  Definition ghd : Z := 512.
  (* config.json = 4 (full-attention layers) *)
  Definition gnkv : Z := 4.
  (* config.json = 1024 *)
  Definition window : Z := 1024.
  (* config.json = 262144 *)
  Definition vocab : Z := 262144.
  (* drafter config.json = 32000 *)
  Definition draft_vocab : Z := 32000.
End S.
Import S.

Lemma layer_mix : n_slide + n_full = nlayers.
Proof. vm_compute. reflexivity. Qed.

(* ---- verify-path weight traffic, one forward pass ---- *)
(* fused [q;k;v] bf16 TN GEMM, 50 sliding layers
   - gemma4.rs:193-200 (row-concatenated [q;k;v] Linear, fused at load)
   - gemma4.rs:2137 (attention_tree -> attn.qkv_forward)
   - gemma4.rs:3127-3153 (load_qkv_fused: weights.get(name, dtype) at model dtype bf16 -- no quantization path exists for attention)
   - config.json quantization_config.ignore lists every layers.N.self_attn* -- attention is NOT NVFP4
   - checkpoint witness: layers.6.self_attn.{q,k,v}_proj.weight BF16 [8192,5376]/[4096,5376]/[4096,5376]
*)
Definition qkv_sliding_bytes : Z := n_slide * (nh*hd + 2*(nkv*hd)) * h * 2.
Lemma qkv_sliding_bytes_val : qkv_sliding_bytes = 8808038400.
Proof. vm_compute. reflexivity. Qed.

(* fused [q;k] bf16 TN GEMM, 10 full-attention layers (k_eq_v: no V block)
   - gemma4.rs:196-200 (k_eq_v full layers have no V block; V reuses the pre-norm K slice -- we read LESS weight than vLLM here)
   - gemma4.rs:3146-3151 (has_v=false concatenates only [q;k])
   - config.json text_config.attention_k_eq_v = true
   - checkpoint witness: layers.5.self_attn.q_proj BF16 [16384,5376], k_proj [2048,5376], NO v_proj tensor
*)
Definition qkv_full_bytes : Z := n_full * (nh*ghd + gnkv*ghd) * h * 2.
Lemma qkv_full_bytes_val : qkv_full_bytes = 1981808640.
Proof. vm_compute. reflexivity. Qed.

(* o_proj bf16 TN GEMM, sliding layers
   - gemma4.rs:2254 (attention_tree -> attn.o_proj.forward)
   - gemma4.rs:3155-3176 (load_attn_proj: bf16, Linear::new)
   - checkpoint witness: layers.6.self_attn.o_proj.weight BF16 [5376,8192]
*)
Definition o_sliding_bytes : Z := n_slide * h * (nh*hd) * 2.
Lemma o_sliding_bytes_val : o_sliding_bytes = 4404019200.
Proof. vm_compute. reflexivity. Qed.

(* o_proj bf16 TN GEMM, full-attention layers
   - gemma4.rs:2254
   - checkpoint witness: layers.5.self_attn.o_proj.weight BF16 [5376,16384]
*)
Definition o_full_bytes : Z := n_full * h * (nh*ghd) * 2.
Lemma o_full_bytes_val : o_full_bytes = 1761607680.
Proof. vm_compute. reflexivity. Qed.

(* fused gate_up NVFP4 GEMM (packed u4 pairs + fp8 scale factors), all 60 layers
   - gemma4.rs:2380-2381 (mlp_forward -> gate_up_proj.forward)
   - gemma4.rs:1838-1849 (load_mlp_proj_fused_pair -> NVFP4 path)
   - gemma4.rs:3178-3223 (load_mlp_proj: NVFP4 unless ignored; MLP is not in the ignore list)
   - checkpoint witness: layers.N.mlp.gate_proj.weight U8 [21504,2688] (=inter*h/2 bytes) + weight_scale F8_E4M3 [21504,336] (=inter*h/16 bytes), same for up_proj
*)
Definition mlp_gate_up_bytes : Z := nlayers * 2 * ((inter*h)/2 + (inter*h)/16).
Lemma mlp_gate_up_bytes_val : mlp_gate_up_bytes = 7803371520.
Proof. vm_compute. reflexivity. Qed.

(* down_proj NVFP4 GEMM, all 60 layers
   - gemma4.rs:2387,2396 (mlp_forward -> down_proj.forward)
   - checkpoint witness: layers.N.mlp.down_proj.weight U8 [5376,10752] + weight_scale F8_E4M3 [5376,1344]
*)
Definition mlp_down_bytes : Z := nlayers * ((h*inter)/2 + (h*inter)/16).
Lemma mlp_down_bytes_val : mlp_down_bytes = 3901685760.
Proof. vm_compute. reflexivity. Qed.

(* dense bf16 lm_head GEMM over all k rows (tied embedding matrix, read in full every verify forward)
   - gemma4.rs:2361,2366 (default path: lm_head.forward_dense(final_norm(hidden)); the int8 variant is DEFAULT-ON since 2026-08-11 via NV_VERIFY_LMHEAD_INT8 (=0 reverts); it measured slower only as v1, which was STAGE-bound at K=5376; the v2 normx_mk + gemv_i8_prenormed_mk kernel gives -0.82 ms/round served with 48/48 argmax agreement)
   - gemma4.rs:421-428 (tie_word_embeddings -> lm_head = embed matrix)
   - config.json quantization_config.ignore includes lm_head
   - checkpoint witness: model.language_model.embed_tokens.weight BF16 [262144,5376]
*)
Definition lm_head_bytes : Z := vocab * h * 2.
Lemma lm_head_bytes_val : lm_head_bytes = 2818572288.
Proof. vm_compute. reflexivity. Qed.

(* Residual small tensors read each forward (RMSNorm gammas, layer_scalars,
   per-proj scale scalars): safetensors language_model total minus the GEMM
   formulas above; asserted < 16 MiB at generation (2664472 B). *)
Definition misc_small_bytes : Z := 2664472.

Definition verify_weight_bytes : Z :=
  qkv_sliding_bytes + qkv_full_bytes + o_sliding_bytes + o_full_bytes + mlp_gate_up_bytes + mlp_down_bytes + lm_head_bytes + misc_small_bytes.

(* Independent inventory: sum of every model.language_model.* tensor's byte
   size from the safetensors headers (vision tower excluded -- never touched
   on the text decode path; tied embed counted once and read in full by the
   dense lm_head GEMM). The equality below is the manifest<->checkpoint
   cross-check, re-proved inside the kernel. *)
Definition safetensors_language_model_bytes : Z := 31481767960.
Lemma verify_weight_crosscheck :
  verify_weight_bytes = safetensors_language_model_bytes.
Proof. vm_compute. reflexivity. Qed.
Lemma verify_weight_bytes_val : verify_weight_bytes = 31481767960.
Proof. vm_compute. reflexivity. Qed.

(* ---- committed-KV read traffic (unique-byte lower bound) ---- *)
(* tree_verify_attn committed-prefix K/V stream (bf16 verify cache at HEAD; NV_GEMMA4_FP8_KV opt-in halves this)
   - tree_verify_attn.cu:92-108 (per position p in [win_start, nc): one K row and one V row of HD bf16 per kv head)
   - tree_verify_attn.cu:73-79 (win_start = max(0, qpos-(window-1)); WindowClamp.committed_range_exact proves this equals the attention-set semantics)
   - gemma4.rs:828 (verify cache is bf16 unless NV_GEMMA4_FP8_KV set)
   - full layers: K counted once and V not counted (k_eq_v layers share K/V content; unique-byte lower bound)
   - sliding layers: union over the K tree queries of the clamped ranges covers min(ctx, window-1) positions (query 0 at qpos=nc attends [nc-window+1, nc)); K and V are distinct buffers -> *2
   NOTE: This is a UNIQUE-BYTE lower bound: each counted byte must cross HBM at least once per forward. The kernel actually re-reads per kv-head-group and per query (diag-budget measured ~20x once-read on the ctx slope), so the true traffic is far above this floor.
*)
Definition kv_read_bytes (ctx : Z) : Z :=
  n_full * ctx * (gnkv*ghd) * 2
  + n_slide * (Z.min ctx (window - 1)) * (nkv*hd) * 2 * 2.

Lemma kv_read_bytes_mono :
  forall a b, 0 <= a -> a <= b -> kv_read_bytes a <= kv_read_bytes b.
Proof. intros; unfold kv_read_bytes; cbv [S.h S.inter S.nlayers S.n_slide S.n_full S.nh S.hd S.nkv S.ghd S.gnkv S.window S.vocab S.draft_vocab]; lia. Qed.

Definition verify_min_traffic (ctx : Z) : Z :=
  verify_weight_bytes + kv_read_bytes ctx.

Lemma verify_min_traffic_at_256 : verify_min_traffic 256 = 31701968920.
Proof. vm_compute. reflexivity. Qed.
Lemma verify_min_traffic_at_262144 :
  verify_min_traffic 262144 = 43057227800.
Proof. vm_compute. reflexivity. Qed.

(* ---- drafter chain-step weight traffic ---- *)
(* drafter q/k/v bf16 GEMMs over block_in = [embed(token); hidden] (input width 2h)
   - eagle3_loader.rs:525 (q_proj.forward(block_in)) and adjacent k/v
   - eagle3_loader.rs:600-620 (step_block_in_dev: concat embed+hidden -> 2h input width)
   - drafter checkpoint witness: layers.0.self_attn.q_proj.weight BF16 [8192,10752], k/v [4096,10752]
*)
Definition draft_qkv_bytes : Z := ((nh*hd) + 2*(nkv*hd)) * (2*h) * 2.
Lemma draft_qkv_bytes_val : draft_qkv_bytes = 352321536.
Proof. vm_compute. reflexivity. Qed.

(* drafter o_proj bf16 GEMM
   - eagle3_loader.rs:552
   - drafter checkpoint: o_proj BF16 [5376,8192]
*)
Definition draft_o_bytes : Z := h * (nh*hd) * 2.
Lemma draft_o_bytes_val : draft_o_bytes = 88080384.
Proof. vm_compute. reflexivity. Qed.

(* drafter gate/up/down bf16 GEMMs
   - eagle3_loader.rs:555-558
   - drafter checkpoint: gate/up [21504,5376], down [5376,21504] BF16
*)
Definition draft_mlp_bytes : Z := 3 * inter * h * 2.
Lemma draft_mlp_bytes_val : draft_mlp_bytes = 693633024.
Proof. vm_compute. reflexivity. Qed.

(* drafter lm_head bf16 GEMM (draft vocab)
   - eagle3_loader.rs:564
   - drafter checkpoint: lm_head.weight BF16 [32000,5376]
*)
Definition draft_head_bytes : Z := draft_vocab * h * 2.
Lemma draft_head_bytes_val : draft_head_bytes = 344064000.
Proof. vm_compute. reflexivity. Qed.

(* drafter RMSNorm gammas (hidden_norm, input_layernorm, post_attention_layernorm, final norm)
   - drafter checkpoint: four [5376] BF16 norm tensors
*)
Definition draft_norm_bytes : Z := 4 * h * 2.
Lemma draft_norm_bytes_val : draft_norm_bytes = 43008.
Proof. vm_compute. reflexivity. Qed.

(* Excluded from the per-step floor (all exclusions only WEAKEN the bound):
   - embed_tokens: shared with target (server log: 'sharing target embedding'); per-step access is a single-row gather (h*2 bytes), counted as slack
   - fc: fc.weight [5376,16128] maps the 3 concatenated aux hiddens once per ROUND (context-row encode, chain_draft_cached_cond eagle3_loader.rs:738+), not per chain step; omitting it only weakens the draft floor
   - d2t_t2d: 256 KiB + 256 KiB lookup tables, slack
   - activations_and_writes: all activation reads/writes, KV appends, rope/rmsnorm traffic are uncounted slack in every floor
*)
Definition draft_step_weight_bytes : Z :=
  draft_qkv_bytes + draft_o_bytes + draft_mlp_bytes + draft_head_bytes + draft_norm_bytes.

(* Cross-check vs the drafter checkpoint (same tensors, safetensors scan). *)
Definition safetensors_draft_step_bytes : Z := 1478141952.
Lemma draft_step_crosscheck :
  draft_step_weight_bytes = safetensors_draft_step_bytes.
Proof. vm_compute. reflexivity. Qed.
Lemma draft_step_weight_bytes_val : draft_step_weight_bytes = 1478141952.
Proof. vm_compute. reflexivity. Qed.
