from __future__ import annotations

SAMPLE_RATE = 16_000
WINDOW_SAMPLES = 512
CONTEXT_SAMPLES = 64
INPUT_SAMPLES = CONTEXT_SAMPLES + WINDOW_SAMPLES
VAD_FAILURE_THRESHOLD = 3

PREFIX_PADDING_MS = 300
SILENCE_DURATION_MS = 350
SPEECH_THRESHOLD = 0.5

MIN_SPEECH_MS = 100

MAX_VAD_WINDOW_MS = 3_000
MAX_VAD_WINDOW_SAMPLES = MAX_VAD_WINDOW_MS * SAMPLE_RATE // 1_000
MIN_SPEECH_DURATION_MS = 100
MAX_SPEECH_DURATION_S = 30.0
MIN_SILENCE_AT_MAX_SPEECH_MS = 98
NEG_THRESHOLD_DELTA = 0.15
NEG_THRESHOLD_FLOOR = 0.01

MAX_PROB_RING = (MAX_VAD_WINDOW_SAMPLES + WINDOW_SAMPLES - 1) // WINDOW_SAMPLES

INPUT_AUDIO_KEY = "input"
INPUT_STATE_KEY = "state"
INPUT_SR_KEY = "sr"
OUTPUT_PROB_KEY = "output"
OUTPUT_STATE_KEY = "stateN"
