from __future__ import annotations

QWEN3_TTS_MODELS = "QWEN3_TTS_MODELS"
QWEN3_TTS_MODEL = "QWEN3_TTS_MODEL"
QWEN3_TTS_DEVICE = "QWEN3_TTS_DEVICE"
QWEN3_TTS_DTYPE = "QWEN3_TTS_DTYPE"
QWEN3_TTS_HOST = "QWEN3_TTS_HOST"
QWEN3_TTS_PORT = "QWEN3_TTS_PORT"
QWEN3_TTS_BATCH_WINDOW_MS = "QWEN3_TTS_BATCH_WINDOW_MS"

QWEN3_OMNI_MODEL = "QWEN3_OMNI_MODEL"
QWEN3_OMNI_DISABLE_TALKER = "QWEN3_OMNI_DISABLE_TALKER"

QWEN3_ALIGNER_MODEL = "QWEN3_ALIGNER_MODEL"

GEMMA_MODEL = "GEMMA_MODEL"
GEMMA_ATTN_IMPL = "GEMMA_ATTN_IMPL"
GEMMA_COMPILE = "GEMMA_COMPILE"

KOKORO_ENABLE = "KOKORO_ENABLE"
KOKORO_VOICES_DIR = "KOKORO_VOICES_DIR"
KOKORO_MODEL_FILE = "KOKORO_MODEL_FILE"
KOKORO_ONNX_PROVIDER = "KOKORO_ONNX_PROVIDER"

PHONEMIZER_ESPEAK_LIBRARY = "PHONEMIZER_ESPEAK_LIBRARY"
ESPEAK_DATA_PATH = "ESPEAK_DATA_PATH"

DIAR_SEGMENTATION_MODEL_FILE = "DIAR_SEGMENTATION_MODEL_FILE"
DIAR_EMBEDDING_MODEL_FILE = "DIAR_EMBEDDING_MODEL_FILE"
DIAR_THRESHOLD = "DIAR_THRESHOLD"
DIAR_MAX_SPEAKERS = "DIAR_MAX_SPEAKERS"
DIAR_MIN_SPAN_FRAMES = "DIAR_MIN_SPAN_FRAMES"
DIAR_MEDIAN_FILTER_FRAMES = "DIAR_MEDIAN_FILTER_FRAMES"

EOU_ENABLED = "EOU_ENABLED"
EOU_KIND = "EOU_KIND"
EOU_EAGERNESS = "EOU_EAGERNESS"
EOU_P_THRESHOLD = "EOU_P_THRESHOLD"
EOU_MIN_DELAY_MS = "EOU_MIN_DELAY_MS"
EOU_MAX_DELAY_MS = "EOU_MAX_DELAY_MS"
EOU_SILENCE_HARD_CAP_MS = "EOU_SILENCE_HARD_CAP_MS"
EOU_INFERENCE_TIMEOUT_MS = "EOU_INFERENCE_TIMEOUT_MS"
EOU_CONTEXT_TURNS = "EOU_CONTEXT_TURNS"
EOU_AUDIO_WINDOW_MS = "EOU_AUDIO_WINDOW_MS"
EOU_AUDIO_PAD_ALIGNMENT = "EOU_AUDIO_PAD_ALIGNMENT"
EOU_THRESHOLDS = "EOU_THRESHOLDS"
EOU_FUSION_RULE = "EOU_FUSION_RULE"
EOU_FUSION_WEIGHT_TEXT = "EOU_FUSION_WEIGHT_TEXT"
EOU_AUDIO_MODEL_PATH = "EOU_AUDIO_MODEL_PATH"
EOU_MODEL_PATH = "EOU_MODEL_PATH"
EOU_TOKENIZER_PATH = "EOU_TOKENIZER_PATH"
EOU_MAX_CONTEXT_TOKENS = "EOU_MAX_CONTEXT_TOKENS"
EOU_EAGER_P_THRESHOLD = "EOU_EAGER_P_THRESHOLD"
EOU_EAGER_MAX_INFLIGHT = "EOU_EAGER_MAX_INFLIGHT"
EOU_EAGER_PERIODIC = "EOU_EAGER_PERIODIC"
EOU_EAGER_INTERVAL_MS = "EOU_EAGER_INTERVAL_MS"
EOU_PREDICTED_TOKEN_BUFFER_CAP = "EOU_PREDICTED_TOKEN_BUFFER_CAP"
EOU_EOT_THRESHOLD = "EOU_EOT_THRESHOLD"
EOU_EAGER_EOT_THRESHOLD = "EOU_EAGER_EOT_THRESHOLD"
MIN_SPEECH_FOR_RESPONSE_MS = "MIN_SPEECH_FOR_RESPONSE_MS"
MIN_SPEECH_FOR_COMMIT_MS = "MIN_SPEECH_FOR_COMMIT_MS"

VAD_MODEL_FILE = "VAD_MODEL_FILE"
VAD_THRESHOLD = "VAD_THRESHOLD"
VAD_PREFIX_PADDING_MS = "VAD_PREFIX_PADDING_MS"
VAD_SILENCE_DURATION_MS = "VAD_SILENCE_DURATION_MS"
VAD_MIN_SPEECH_DURATION_MS = "VAD_MIN_SPEECH_DURATION_MS"
VAD_MAX_SPEECH_DURATION_S = "VAD_MAX_SPEECH_DURATION_S"

SESSION_MAX_DURATION_S = "SESSION_MAX_DURATION_S"
BARGE_IN_DELAY_MS = "BARGE_IN_DELAY_MS"
SPEACHES_PLUS_MODELS = "SPEACHES_PLUS_MODELS"

WS_MAX_MESSAGE_BYTES = "WS_MAX_MESSAGE_BYTES"
WS_OUTBOUND_QUEUE_CAP = "WS_OUTBOUND_QUEUE_CAP"
WS_IDLE_TIMEOUT_S = "WS_IDLE_TIMEOUT_S"
WS_MAX_CONCURRENT_SESSIONS = "WS_MAX_CONCURRENT_SESSIONS"

STT_BACKEND = "STT_BACKEND"

OUTBOUND_QUEUE_CAP_MS = "OUTBOUND_QUEUE_CAP_MS"
OUTBOUND_QUEUE_CAP = "OUTBOUND_QUEUE_CAP"

CHAT_COMPLETION_BASE_URL = "CHAT_COMPLETION_BASE_URL"
CHAT_COMPLETION_API_KEY = "CHAT_COMPLETION_API_KEY"
DEFAULT_REALTIME_CONVERSATION_MODEL = "DEFAULT_REALTIME_CONVERSATION_MODEL"

INSPECT_SESSION_DIR = "INSPECT_SESSION_DIR"
INSPECT_RETENTION_COUNT = "INSPECT_RETENTION_COUNT"
INSPECT_RETENTION_BYTES = "INSPECT_RETENTION_BYTES"
INSPECT_RETENTION_DAYS = "INSPECT_RETENTION_DAYS"

OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
OTEL_EXPORTER_OTLP_PROTOCOL = "OTEL_EXPORTER_OTLP_PROTOCOL"
OTEL_SERVICE_NAME = "OTEL_SERVICE_NAME"

import os as _os

def read_str(name: str, default: str = "") -> str:
    return _os.environ.get(name, default)

def read_str_or_none(name: str) -> str | None:
    raw = _os.environ.get(name, "").strip()
    return raw or None

def read_int(name: str, default: int) -> int:
    raw = _os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        return default

def read_float(name: str, default: float) -> float:
    raw = _os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        return default

def read_bool(name: str, default: bool = False) -> bool:
    raw = _os.environ.get(name, "").strip().lower()
    if not raw:
        return default
    if raw in ("1", "true", "yes", "on", "y", "t"):
        return True
    if raw in ("0", "false", "no", "off", "n", "f"):
        return False
    return default
